// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import css from "./page.module.css";

import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <>
      {/* <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <html lang="en">
        <body>
          <TanStackProvider>
            <Header />
            {children}
            <Footer />
          </TanStackProvider>
        </body>
      </html>
    </>
  );
}
